name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Create Temporary Directory
        id: create_temp_dir
        run: |
          TEMP_DIR=$(mktemp -d)
          echo "TEMP_DIR=$TEMP_DIR" >> $GITHUB_OUTPUT

      - name: Download the Release Asset
        run: |
          url=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | grep "browser_download_url.*hugo-site.zip" | cut -d '"' -f 4)
          curl -L -o "${{ steps.create_temp_dir.outputs.TEMP_DIR }}/hugo-site.zip" "$url"

      - name: Unzip the Release Asset
        run: |
          unzip "${{ steps.create_temp_dir.outputs.TEMP_DIR }}/hugo-site.zip" -d "${{ steps.create_temp_dir.outputs.TEMP_DIR }}/unzipped"
          rm -rf ../../../../public
          mkdir -p ../../../../public
          mv "${{ steps.create_temp_dir.outputs.TEMP_DIR }}/unzipped/public/"* ../../../../public/
          rm -rf "${{ steps.create_temp_dir.outputs.TEMP_DIR }}"
