name: Disk Space Alert

on:
  workflow_dispatch:
  schedule:
    - cron: "* * * * */7"
  workflow_run:
    workflows:
      - Build Hugo site and upload to release
    types:
      - completed

jobs:
  check-disk:
    runs-on: self-hosted
    steps:
      - name: Check Disk Usage
        id: check_disk
        run: |
          DISK_USAGE=$(du -sm ~ | awk '{printf "%.1f", $1 / 1024}')
          TOTAL_DISK=4

          echo "DISK_USAGE=${DISK_USAGE}" >> $GITHUB_OUTPUT
          echo "TOTAL_DISK=${TOTAL_DISK}" >> $GITHUB_OUTPUT

          echo "## 📝 ディスク使用状況レポート" >> $GITHUB_STEP_SUMMARY
          echo "現在のディスクの使用量は ${DISK_USAGE} GB / ${TOTAL_DISK} GB です。" >> $GITHUB_STEP_SUMMARY

      - name: Check Threshold
        run: |
          THRESHOLD=3
          DISK_USAGE=${{ steps.check_disk.outputs.DISK_USAGE }}
          TOTAL_DISK=${{ steps.check_disk.outputs.TOTAL_DISK }}

          if (( $(echo "$DISK_USAGE > $THRESHOLD" | bc -l) )); then
            echo "## ⚠️ 警告: 対応が必要" >> $GITHUB_STEP_SUMMARY
            echo "ディスク使用量が上限に近づいています。" >> $GITHUB_STEP_SUMMARY
            echo "不要なファイルを削除してください。" >> $GITHUB_STEP_SUMMARY
            echo "必要な場合には、情報基盤センターにディスク容量の増量を依頼してください。" >> $GITHUB_STEP_SUMMARY
            exit 1
          else
            echo "## ✅ 正常: 対応は不要" >> $GITHUB_STEP_SUMMARY
            echo "ディスク使用量は正常です。" >> $GITHUB_STEP_SUMMARY
          fi
