  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      # 既存のpublicディレクトリを削除
      - name: Remove Existing Public Directory
        run: |
          pwd  # 現在のディレクトリを表示
          rm -rf ../../../public  # 2つ上の階層のpublicを削除

      # GitHub APIからリリースアセットのダウンロードURLを取得
      - name: Download the Release Asset
        run: |
          pwd  # 現在のディレクトリを表示
          url=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | grep "browser_download_url.*hugo-site.zip" | cut -d '"' -f 4)
          curl -L -o hugo-site.zip "$url"
          
      # ダウンロードしたZIPを解凍し、指定のディレクトリに設置
      - name: Unzip the Hugo Site
        run: |
          pwd  # 現在のディレクトリを表示
          unzip hugo-site.zip -d ../../../public  # 2つ上の階層のpublicディレクトリに解凍

      - name: Cleanup
        run: |
          pwd  # 現在のディレクトリを表示
          rm hugo-site.zip  # ZIPファイルの削除
